# RTF Download URL
# no: copy from control host, yes: download from internet
rtf_download: yes
# rtf_download: no
rtf_installer: "https://runtime-fabric.s3.amazonaws.com/installer/runtime-fabric-1.1.1583954392-3121bcd.tar.gz"
# can be copy/scp from ansible control hosts
# rtf_installer: installers/runtime-fabric-1.1.1572976203-3ad8a93.tar.gz
# working directory
install_dir: /opt/anypoint/runtimefabric
# rtf install variables
rtf_license: # put base64 encoded license.lic file here `base64 </path/to/license.lic`
rtf_cluster_name: runtime-fabric
rtf_token: gravity-cluster-token
rtf_activation: # PUT new RTF cluster activation data here
# http proxy setting - http://proxy.company.com:3128
http_proxy:
no_proxy:
# socks5 proxy setting for anypoint monitoring - socks5://socks5.company.com:1080
monitoring_proxy:
# rtf backup dir
rtf_backup_dir: "/var/lib/gravity/backup"
# mandatory package to install if any -- UNCOMMENT List Below to set it up
# packages:
# - bind-utils
# - telnet
