---
- hosts: all
  tasks:
    - name: Check if gravity is in PATH
      shell: "gravity version >/dev/null 2>&1"
      register: result
    - name: Uninstall gravity
      become: yes
      shell: "gravity system uninstall --confirm"
      when: result.rc == 0
    - name: remove /untimefabric directory structure
      become: yes
      file:
        path: /opt/anypoint/runtimefabric
        state: absent
    - name: controllers with dedicated etcd device or not
      become: yes
      shell: "findmnt /var/lib/gravity/planet/etcd"
      register: etcd_device
    - name: umount etcd device for controllers
      become: yes
      shell: "umount -l /var/lib/gravity/planet/etcd"
      when: etcd_device.rc == 0
    - name: umount docker ce device
      become: yes
      shell: "umount -l /var/lib/gravity"
    - name: remove fstab entries
      become: yes
      shell: "sed -i '/RTF/d' /etc/fstab"
    - name: reboot all VMs to get clean state
      become: yes
      shell: "systemctl reboot"
