---
- hosts: all
  tasks:
    - name: Check if gravity is in PATH
      shell: "gravity version >/dev/null 2>&1"
      register: result
    - name: Uninstall gravity
      become: yes
      shell: "gravity system uninstall --confirm"
      when: result.rc == 0
    - name: remove /untimefabric directory structure
      become: yes
      file:
        path: /opt/anypoint/runtimefabric
        state: absent
    - name: remove fstab entrie
      become: yes
      shell: "sed -i '/RTF/d' /etc/fstab"
    - name: umount etcd and docker ce devices
      become: yes
      shell: "umount -l /var/lib/gravity/planet/etcd; umount -l /var/lib/gravity"
    - name: reboot all VMs to get clean state
      become: yes
      shell: "systemctl reboot"
